### ISSUE TITLE
TypeError: client.getApiKey is not a function

### ISSUE THREAD

**Issue by Uriziel01** [oncletom/hexo-algolia#20]
When Im trying to run `./node_modules/.bin/hexo algolia` I'm getting error `TypeError: client.getApiKey is not a function`.

I've already exported `HEXO_ALGOLIA_INDEXING_KEY` and triple checked all my configuration.
Is this a bug or Im just doing something wrong?

If You need full stack dump to check it just let me know 😄

**Comment by thom4parisot** [comment]
@Uriziel01 hm, it's weird. It comes from the algolia client, provided by the `algoliasearch` package.

What happens when you run this in a terminal?

```bash
$ npm ls | grep algoliasearch
```

What is the version of the `hexo-algolia` plugin you use?

```bash
$ npm ls | grep hexo-algolia
```

If you could try with the latest version of `hexo-algolia` and then print the entire stack trace if the problem happens, it would be helpful indeed 🙂

**Comment by Uriziel01** [comment]
Sorry for no messages for sucha long period of time.
I've updated package right now and it works like a charm. So no complains on my end 👍 Thank you!

**Comment by thom4parisot** [comment]
No problem @Uriziel01, glad it works on your side now 🙂
