### ISSUE TITLE
Not indexing contents in the newest version?

### ISSUE THREAD

**Issue by tomdai** [oncletom/hexo-algolia#26]
I was using hexo-algolia 0.1.1 and updated it to 1.2.3 just now.

I found that the new data uploaded to Algolia now do not include the posts' contents but only titles and excerpts. However, most of my website's posts do not have excerpts.

Is there any way to work this out? By the way, it would be really great if I can choose what to index.

Thanks!

**Comment by thom4parisot** [comment]
Hi Tomi,

thanks for raising the issue and sorry for the inconvenience.
I made the decision due to #24 to solve #15. Aka the blog post content was too long and thus got rejected by algolia.

I was thinking of indexing only a limited part of the content to put an emphasis on the first paragraphs.

Even though the posts could be reindexed again, something has to be done in regard of the longest ones (> 100K). Their content will have to be stripped down or something like that but I'd rather have a fair and predictable behaviour against all types of content.

Your thoughts are welcome

**Comment by tomdai** [comment]
If that's the case, I believe you made the right decision.

I'll just stick to the old version for now, try to add excerpts to all the posts, and update to the newest version when the excerpts are done.

However, I still hope you can add the option to let us choose whether to index the contents or not.

Thank you for making this great plugin anyway!

**Comment by thom4parisot** [comment]
> If that's the case, I believe you made the right decision.

Well, maybe not, so don't necessarily do update all your content.

You say you are going to try to add excerpts – is that enough for you to be indexed? Any reason you have not written them previously?

> However, I still hope you can add the option to let us choose whether to index the contents or not.

I think this is a good idea, especially as it would enable people to index additional post and pages metadata – at the moment, only a handful amount of them are stored.

**Comment by thom4parisot** [comment]
Closing this, as it has been done with #24.
